type PermissionSeed = {
  permissionKey: string
  name: string
  codename: string
  appLabel?: string
  modelName?: string
}

const PERMISSION_KEYS: string[] = [
  'pmc_api.add_applicantdetail',
  'pmc_api.add_applicantdocument',
  'pmc_api.add_applicantfieldresponse',
  'pmc_api.add_applicantmanualfields',
  'pmc_api.add_applicationassignment',
  'pmc_api.add_businessprofile',
  'pmc_api.add_byproduct',
  'pmc_api.add_collector',
  'pmc_api.add_consumer',
  'pmc_api.add_districtplasticcommitteedocument',
  'pmc_api.add_inspectionreport',
  'pmc_api.add_plasticitem',
  'pmc_api.add_producer',
  'pmc_api.add_product',
  'pmc_api.add_psidtracking',
  'pmc_api.add_rawmaterial',
  'pmc_api.add_recycler',
  'pmc_api.change_applicantdetail',
  'pmc_api.change_applicantmanualfields',
  'pmc_api.change_applicationassignment',
  'pmc_api.change_businessprofile',
  'pmc_api.change_collector',
  'pmc_api.change_consumer',
  'pmc_api.change_inspectionreport',
  'pmc_api.change_producer',
  'pmc_api.change_recycler',
  'pmc_api.delete_applicantdetail',
  'pmc_api.delete_businessprofile',
  'pmc_api.delete_inspectionreport',
  'pmc_api.view_applicantdetail',
  'pmc_api.view_applicantdocument',
  'pmc_api.view_applicantfee',
  'pmc_api.view_applicantfieldresponse',
  'pmc_api.view_applicantmanualfields',
  'pmc_api.view_applicationassignment',
  'pmc_api.view_businessprofile',
  'pmc_api.view_byproduct',
  'pmc_api.view_collector',
  'pmc_api.view_consumer',
  'pmc_api.view_district',
  'pmc_api.view_districtplasticcommitteedocument',
  'pmc_api.view_inspectionreport',
  'pmc_api.view_license',
  'pmc_api.view_plasticitem',
  'pmc_api.view_producer',
  'pmc_api.view_product',
  'pmc_api.view_psidtracking',
  'pmc_api.view_rawmaterial',
  'pmc_api.view_recycler',
  'pmc_api.view_singleuseplasticssnapshot',
  'pmc_api.view_tehsil',
]

const buildPermission = (permissionKey: string): PermissionSeed => {
  const [appLabel, codename] = permissionKey.split('.')
  const action = codename.split('_')[0]
  const modelName = codename.split('_').slice(1).join('_')
  const label = modelName.replace(/_/g, ' ')
  const name = `Can ${action} ${label}`
  return { permissionKey, name, codename, appLabel, modelName }
}

const PERMISSION_SEEDS: PermissionSeed[] = PERMISSION_KEYS.map(buildPermission)

const DEFAULT_GROUP_PERMISSIONS: Record<string, string[]> = {
  APPLICANT: [
    'pmc_api.view_applicantdetail',
    'pmc_api.add_applicantdetail',
    'pmc_api.change_applicantdetail',
    'pmc_api.view_applicantdocument',
    'pmc_api.add_applicantdocument',
    'pmc_api.view_businessprofile',
    'pmc_api.add_businessprofile',
    'pmc_api.change_businessprofile',
    'pmc_api.view_producer',
    'pmc_api.add_producer',
    'pmc_api.change_producer',
    'pmc_api.view_consumer',
    'pmc_api.add_consumer',
    'pmc_api.change_consumer',
    'pmc_api.view_collector',
    'pmc_api.add_collector',
    'pmc_api.change_collector',
    'pmc_api.view_recycler',
    'pmc_api.add_recycler',
    'pmc_api.change_recycler',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
    'pmc_api.view_product',
    'pmc_api.view_byproduct',
    'pmc_api.view_plasticitem',
    'pmc_api.view_rawmaterial',
    'pmc_api.view_license',
    'pmc_api.add_psidtracking',
    'pmc_api.view_psidtracking',
  ],
  LSO: [
    'pmc_api.view_applicantdetail',
    'pmc_api.change_applicantdetail',
    'pmc_api.view_applicantdocument',
    'pmc_api.view_businessprofile',
    'pmc_api.view_applicantfee',
    'pmc_api.view_psidtracking',
    'pmc_api.view_license',
    'pmc_api.view_applicationassignment',
    'pmc_api.add_applicationassignment',
    'pmc_api.change_applicationassignment',
    'pmc_api.view_applicantfieldresponse',
    'pmc_api.view_applicantmanualfields',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
    'pmc_api.view_product',
    'pmc_api.view_byproduct',
    'pmc_api.view_plasticitem',
    'pmc_api.view_rawmaterial',
  ],
  LSM: [
    'pmc_api.view_applicantdetail',
    'pmc_api.change_applicantdetail',
    'pmc_api.view_applicantdocument',
    'pmc_api.view_businessprofile',
    'pmc_api.view_applicantfee',
    'pmc_api.view_psidtracking',
    'pmc_api.view_license',
    'pmc_api.view_applicationassignment',
    'pmc_api.add_applicationassignment',
    'pmc_api.change_applicationassignment',
    'pmc_api.view_applicantfieldresponse',
    'pmc_api.view_applicantmanualfields',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
    'pmc_api.view_product',
    'pmc_api.view_byproduct',
    'pmc_api.view_plasticitem',
    'pmc_api.view_rawmaterial',
  ],
  LSM2: [
    'pmc_api.view_applicantdetail',
    'pmc_api.change_applicantdetail',
    'pmc_api.view_applicantdocument',
    'pmc_api.view_businessprofile',
    'pmc_api.view_applicantfee',
    'pmc_api.view_psidtracking',
    'pmc_api.view_license',
    'pmc_api.view_applicationassignment',
    'pmc_api.add_applicationassignment',
    'pmc_api.change_applicationassignment',
    'pmc_api.view_applicantfieldresponse',
    'pmc_api.view_applicantmanualfields',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
    'pmc_api.view_product',
    'pmc_api.view_byproduct',
    'pmc_api.view_plasticitem',
    'pmc_api.view_rawmaterial',
  ],
  TL: [
    'pmc_api.view_applicantdetail',
    'pmc_api.change_applicantdetail',
    'pmc_api.view_applicantdocument',
    'pmc_api.view_businessprofile',
    'pmc_api.view_applicantfee',
    'pmc_api.view_psidtracking',
    'pmc_api.view_license',
    'pmc_api.view_applicationassignment',
    'pmc_api.add_applicationassignment',
    'pmc_api.change_applicationassignment',
    'pmc_api.view_applicantfieldresponse',
    'pmc_api.view_applicantmanualfields',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
    'pmc_api.view_product',
    'pmc_api.view_byproduct',
    'pmc_api.view_plasticitem',
    'pmc_api.view_rawmaterial',
  ],
  DO: [
    'pmc_api.view_applicantdetail',
    'pmc_api.change_applicantdetail',
    'pmc_api.view_applicantdocument',
    'pmc_api.view_businessprofile',
    'pmc_api.view_applicantfee',
    'pmc_api.view_psidtracking',
    'pmc_api.view_license',
    'pmc_api.view_applicationassignment',
    'pmc_api.add_applicationassignment',
    'pmc_api.change_applicationassignment',
    'pmc_api.view_applicantfieldresponse',
    'pmc_api.view_applicantmanualfields',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
    'pmc_api.view_product',
    'pmc_api.view_byproduct',
    'pmc_api.view_plasticitem',
    'pmc_api.view_rawmaterial',
    'pmc_api.view_inspectionreport',
  ],
  DEO: [
    'pmc_api.view_applicantdetail',
    'pmc_api.change_applicantdetail',
    'pmc_api.view_applicantdocument',
    'pmc_api.view_businessprofile',
    'pmc_api.view_applicantfee',
    'pmc_api.view_psidtracking',
    'pmc_api.view_license',
    'pmc_api.view_applicationassignment',
    'pmc_api.add_applicationassignment',
    'pmc_api.change_applicationassignment',
    'pmc_api.view_applicantfieldresponse',
    'pmc_api.view_applicantmanualfields',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
    'pmc_api.view_product',
    'pmc_api.view_byproduct',
    'pmc_api.view_plasticitem',
    'pmc_api.view_rawmaterial',
    'pmc_api.view_inspectionreport',
  ],
  DG: [
    'pmc_api.view_applicantdetail',
    'pmc_api.change_applicantdetail',
    'pmc_api.view_applicantdocument',
    'pmc_api.view_businessprofile',
    'pmc_api.view_applicantfee',
    'pmc_api.view_psidtracking',
    'pmc_api.view_license',
    'pmc_api.view_applicationassignment',
    'pmc_api.add_applicationassignment',
    'pmc_api.change_applicationassignment',
    'pmc_api.view_applicantfieldresponse',
    'pmc_api.view_applicantmanualfields',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
    'pmc_api.view_product',
    'pmc_api.view_byproduct',
    'pmc_api.view_plasticitem',
    'pmc_api.view_rawmaterial',
    'pmc_api.view_inspectionreport',
  ],
  'Download License': [
    'pmc_api.view_license',
    'pmc_api.view_applicantdetail',
    'pmc_api.view_businessprofile',
    'pmc_api.view_applicantdocument',
    'pmc_api.view_psidtracking',
    'pmc_api.view_applicantfee',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
  ],
  Inspector: [
    'pmc_api.view_inspectionreport',
    'pmc_api.add_inspectionreport',
    'pmc_api.change_inspectionreport',
    'pmc_api.view_district',
    'pmc_api.view_tehsil',
  ],
}

module.exports = { PERMISSION_SEEDS, DEFAULT_GROUP_PERMISSIONS }
