import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'signUp',
        path: '/spuid-signup',
        title: 'New Application',
        translateKey: 'nav.spuid.signup',
        icon: 'FaUserPlus',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'home',
        path: '/home',
        title: 'My Applications',
        translateKey: 'nav.home1',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'home.license',
        path: '/home-license',
        title: 'Download License',
        translateKey: 'nav.home1',
        icon: 'MdDownload', // Material Icons
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'track.application',
        path: '/track-application',
        title: 'Track Application',
        translateKey: 'nav.home1',
        icon: 'MdOutlineTrackChanges', // Material Icons
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'analyticsMenu',
        path: '',
        title: 'Analytics',
        translateKey: 'nav.collapseMenu.analyticsMenu',
        icon: 'MdAnalytics',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [
            'Analytics',
            'Analytics1',
            'Analytics2',
            'Analytics3',
            'Admin',
            'DEO',
            'DG',
            'DO',
            'LSM',
            'LSO',
            'TL',
            'Super',
        ],
        subMenu: [
            {
                key: 'analyticsMenu.analytics1',
                path: '/analytics1',
                title: 'Summary Analytics',
                translateKey: 'nav.analyticsMenu.analytics1',
                icon: 'FaChartLine',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [
                    'Analytics1',
                    'Admin',
                    'DEO',
                    'DG',
                    'DO',
                    'LSM',
                    'LSO',
                    'TL',
                    'Super',
                ],
                subMenu: [],
            },
            {
                key: 'analyticsMenu.analytics2',
                path: '/collapse-menu-item-view-2',
                title: 'Downloadable Reports',
                translateKey: 'nav.collapseMenu.item22',
                icon: 'MdDownload',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Analytics2'],
                subMenu: [],
            },
            {
                key: 'analyticsMenu.analytics3',
                path: '/collapse-menu-item-view-3',
                title: 'Downloadable Reports',
                translateKey: 'nav.collapseMenu.item22',
                icon: 'MdDownload',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Analytics3'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'auth.mis',
        path: '',
        title: 'Management Information System',
        translateKey: 'nav.collapseMenu.analyticsMenu',
        icon: 'FaDatabase',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [
            'Analytics3',
            'EEC',
            'Admin',
            'DEO',
            'DG',
            'DO',
            'LSM',
            'LSO',
            'TL',
            'Super',
            '',
        ],
        subMenu: [
            {
                key: 'auth.mis.directory',
                path: '/auth/mis/directory',
                title: 'Public Directory',
                translateKey: 'nav.analyticsMenu.analytics1',
                icon: 'FaAddressBook',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [
                    'Super',
                    'EEC',
                    'Admin',
                    'DEO',
                    'DG',
                    'DO',
                    'LSM',
                    'LSO',
                    'TL',
                    'Super',
                    '',
                ],
                subMenu: [],
            },
            {
                key: 'auth.mis.recycling-efficency',
                path: '/auth/mis/recycling-efficiency',
                title: 'Recycling Efficiency',
                translateKey: 'nav.analyticsMenu.analytics1',
                icon: 'MdRecycling',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Super'],
                subMenu: [],
            },
            {
                key: 'auth.mis.clubs-directory',
                path: '/auth/mis/clubs/directory',
                title: 'Educational Environmental Club Directory',
                translateKey: 'nav.analyticsMenu.analytics1',
                icon: 'FaAddressBook',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [
                    'Super',
                    'EEC',
                    'Admin',
                    'DEO',
                    'DG',
                    'DO',
                    'LSM',
                    'LSO',
                    'TL',
                    'Super',
                    '',
                ],
                subMenu: [],
            },
        ],
    },
    {
        key: 'payment.dashboard',
        path: '/payment',
        title: 'Payments',
        translateKey: 'nav.payment.dashboard',
        icon: 'MdPayments',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'notifications',
        path: '/notifications',
        title: 'Notifications',
        translateKey: 'nav.notifications',
        icon: 'MdNotifications',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'application.form',
        path: '/application',
        title: 'Application Form',
        translateKey: 'nav.application.form',
        icon: 'MdEditDocument',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'settings',
        path: '/settings',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'MdSettings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'auth.EPAOperations',
        path: '',
        title: 'EPA Operations',
        translateKey: 'nav.collapseMenu.analyticsMenu',
        icon: 'FaTools',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['TL', 'DO', 'DEO', 'DG', 'LSO', 'Admin', 'Inspector'],
        subMenu: [
            {
                key: 'auth.EPAOperation.ReportViolation',
                path: '/auth/EPAOperations/ReportViolation',
                title: 'Add New Inspection',
                translateKey: 'nav.analyticsMenu.ReportViolation',
                icon: 'MdAssignmentTurnedIn',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [
                    'TL',
                    'DO',
                    'DEO',
                    'DG',
                    'LSO',
                    'Admin',
                    'Inspector',
                ],
                subMenu: [],
            },
            {
                key: 'auth.EPAOperation.AllInspections',
                path: '/auth/EPAOperations/AllInspections',
                title: 'All Inspections',
                translateKey: 'nav.analyticsMenu.AllInspections',
                icon: 'MdFactCheck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [
                    'TL',
                    'DO',
                    'DEO',
                    'DG',
                    'LSO',
                    'Admin',
                    'Inspector',
                ],
                subMenu: [],
            },
            {
                key: 'auth.EPAOperation.Dashboard',
                path: '/auth/EPAOperation/Dashboard',
                title: 'Dashboard',
                translateKey: 'nav.analyticsMenu.analytics1',
                icon: 'MdDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [
                    'TL',
                    'DO',
                    'DEO',
                    'DG',
                    'LSO',
                    'Admin',
                    'Inspector',
                ],
                subMenu: [],
            },
            {
                key: 'auth.EPAOperation.UserProfile',
                path: '/auth/EPAOperation/UserProfile',
                title: 'User Profile - Field Inspectors',
                translateKey: 'nav.analyticsMenu.analytics1',
                icon: 'FaUserShield',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['DO'],
                subMenu: [],
            },
            {
                key: 'auth.EPAOperation.DocumentDashboard',
                path: '/auth/EPAOperation/DocumentsDashboard',
                title: 'District Documents Dashboard',
                translateKey: 'nav.analyticsMenu.analytics1',
                icon: 'HiOutlineDocumentText',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['DO', 'TL', 'DEO', 'DG', 'LSO', 'Admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'auth.admin',
        path: '',
        title: 'Admin',
        translateKey: 'nav.admin',
        icon: 'MdSecurity',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['Admin', 'Super'],
        subMenu: [
            {
                key: 'auth.admin.permissions',
                path: '/auth/admin/permissions',
                title: 'Permissions Matrix',
                translateKey: 'nav.admin.permissions',
                icon: 'MdSecurity',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Super'],
                subMenu: [],
            },
            {
                key: 'auth.admin.role-dashboard',
                path: '/auth/admin/role-dashboard',
                title: 'Role Dashboards',
                translateKey: 'nav.admin.roleDashboards',
                icon: 'MdDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Super'],
                subMenu: [],
            },
            {
                key: 'auth.admin.api-logs',
                path: '/auth/admin/api-logs',
                title: 'API Logs',
                translateKey: 'nav.admin.apiLogs',
                icon: 'MdReceiptLong',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Super'],
                subMenu: [],
            },
            {
                key: 'auth.admin.audit-logs',
                path: '/auth/admin/audit-logs',
                title: 'Audit Logs',
                translateKey: 'nav.admin.auditLogs',
                icon: 'MdHistory',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Super'],
                subMenu: [],
            },
            {
                key: 'auth.admin.access-logs',
                path: '/auth/admin/access-logs',
                title: 'Access Logs',
                translateKey: 'nav.admin.accessLogs',
                icon: 'MdListAlt',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Super'],
                subMenu: [],
            },
            {
                key: 'auth.admin.service-configs',
                path: '/auth/admin/service-configs',
                title: 'Service Config',
                translateKey: 'nav.admin.serviceConfigs',
                icon: 'MdSettings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Super'],
                subMenu: [],
            },
            {
                key: 'auth.admin.external-tokens',
                path: '/auth/admin/external-tokens',
                title: 'External Tokens',
                translateKey: 'nav.admin.externalTokens',
                icon: 'MdVpnKey',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Super'],
                subMenu: [],
            },
            {
                key: 'auth.admin.reports',
                path: '/auth/admin/reports',
                title: 'Reports & Export',
                translateKey: 'nav.admin.reports',
                icon: 'MdAssessment',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Super'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'register-competition',
        path: '/register-competition',
        title: 'Competition Registration',
        translateKey: 'nav.spuid.signup',
        icon: 'FaClipboardList',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['TEST'],
        subMenu: [],
    },
    {
        key: 'phase5.insights',
        path: '',
        title: 'Insights & Analytics',
        translateKey: 'nav.phase5.insights',
        icon: 'FaMicroscope',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [
            'Analytics',
            'Analytics1',
            'Analytics2',
            'Analytics3',
            'TL',
            'DO',
            'DEO',
            'DG',
            'LSO',
            'Admin',
            'Inspector',
            'Super',
        ],
        subMenu: [
            {
                key: 'gis.visualization',
                path: '/gis/visualization',
                title: 'GIS Visualization',
                translateKey: 'nav.gis.visualization',
                icon: 'FaMapLocationDot',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['TL', 'DO', 'DEO', 'DG', 'LSO', 'Admin', 'Inspector', 'Super'],
                subMenu: [],
            },
            {
                key: 'analytics.advanced',
                path: '/analytics/dashboard',
                title: 'Advanced Analytics',
                translateKey: 'nav.analytics.advanced',
                icon: 'FaChartBar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [
                    'Analytics',
                    'Analytics1',
                    'Analytics2',
                    'Analytics3',
                    'Admin',
                    'DEO',
                    'DG',
                    'DO',
                    'LSM',
                    'LSO',
                    'TL',
                    'Super',
                ],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig

